# This contains params to be used by the stages to train or predict
prepare:
  split: 0.205
  seed: 2021

featurize:
  max_features: 3000
  ngrams: 2

train:
  seed: 2021
  n_est: 150
  min_split: 18
