# It contains all the configs required in the project

artifacts:
  ARTIFACTS_DIR: artifacts
  TRAIN_DATA: train
  TEST_DATA: test
  PREPARED_DATA: prepared

source_data:
  data_dir: data
  data_file: data.xml

